@startuml Transportes

entity Onibus {
    Id
    --
    NumeroDaLinha
    HorarioDePartida
    Passageiros
}

entity Linha {
    Id
    --
    CodigoDaLInha
}

entity Ponto {
    Id
    --
    Rua
    Bairro
    Referencia
}

entity PontoLinha {
    Id
    --
    IdPonto
    IdLinha
}

entity LinhaOnibus {
    Id
    --
    IdOnibus
    IdLinha
}

Onibus --{ LinhaOnibus : 1:n
LinhaOnibus -- Linha : 1:1
Linha --{ PontoLinha : 1:n
Ponto --{ PontoLinha : 1:n

@enduml